# Generated by Django 5.2.7 on 2025-10-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('line', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('geo_location', models.CharField(max_length=100)),
            ],
        ),
    ]
