# Generated by Django 5.2.7 on 2025-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_emailverification_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'verified'], name='feedback_em_email_45b8d2_idx'),
        ),
    ]
