# Generated by Django 5.2 on 2025-11-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.CharField(max_length=100)),
                ('punctuality', models.CharField(blank=True, max_length=50, null=True)),
                ('onboard_info_display', models.CharField(blank=True, max_length=50, null=True)),
                ('onboard_announcements', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_style', models.CharField(blank=True, max_length=50, null=True)),
                ('cleanliness', models.JSONField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('passenger_behavior', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('token', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
