# Generated by Django 4.2.5 on 2025-11-02 22:30
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_ridefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridefeedback',
            name='line_name',
            field=models.CharField(default='missing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridefeedback',
            name='direction',
            field=models.CharField(default='missing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridefeedback',
            name='feedback_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 22, 20)),
            preserve_default=False,
        ),
    ]
